name: Deploy website

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Install dependencies
          working-directory: ./04PracticeProject
          run: npm ci
        - name: Run lint
          working-directory: ./04PracticeProject
          run: npm run lint
        - name: Run tests
          working-directory: ./04PracticeProject
          run: npm test
    build:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Install dependencies
          working-directory: ./04PracticeProject
          run: npm ci
        - name: Build application
          working-directory: ./04PracticeProject
          run: npm run build
    deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Deploy application
          run: echo "Deploying application..." # Replace with actual deployment commands
