name: Events demo

on: 
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
        types:
            - opened
            - edited
            - closed
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Output event data
              run: echo "${{ toJson(github.event) }}"
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci
            - name: Test application
              run: npm test
            - name: Build application
              run: npm run build
            - name: Deploy application
              run: echo "Deploying application..." # Replace with actual deployment commands
