name: Matrix Demo Workflow
on:
  push:
    branches:
      - main
      - matrix
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  matrix-build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12, 18, 20]
        os: [ubuntu-latest, windows-latest]
        include:
          - node-version: 14
            os: ubuntu-latest
        exclude:
          - node-version: 12
            os: windows-latest
    defaults:
      run:
        working-directory: ./04PracticeProject
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: ./04PracticeProject/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: Build application
        run: npm run build
