name: Output information
on:
  workflow_dispatch:
  push:
    branches:
      - output-workflow
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context
        run: |
          echo "GitHub Context:"
          echo "Event Name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"
          echo "${{ toJson(github) }}"
      - name: Output job context
        run: |
          echo "Job Context:"
          echo "Job Name: ${{ job.status }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "${{ toJson(job) }}"
