name: Reusable Test
on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: ${{ inputs.working-directory }}/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run tests
        id: run-tests
        run: npm test
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ inputs.working-directory }}/test.json
