name: Reusable Deploy
on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      artifact-name:
        required: false
        default: 'build-artifacts'
        type: string
    outputs:
      artifact-name:
        description: Name of the artifact uploaded
        value: ${{ inputs.artifact-name }} was uploaded
      result:
        description: Result of the deployment
        value: ${{ jobs.dummy-deploy.outputs.deployment-result }}
jobs:
  dummy-deploy:
    outputs:
      deployment-result: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.working-directory }}
      - name: Dummy deployment step
        run: echo "Deploying from ${{ inputs.working-directory }}"
      - name: Set result output
        id: set-result
        run: echo "step-result=Deployment completed successfully" >> $GITHUB_OUTPUT
