name: Use Reusable Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - matrix

jobs:
    test:
      uses: ./.github/workflows/reusable-test.yaml
      with:
        working-directory: ./04PracticeProject
    build:
      needs: test
      uses: ./.github/workflows/reusable-build.yaml
      with:
        working-directory: ./04PracticeProject
    deploy:
      needs: build
      uses: ./.github/workflows/reusable-deploy.yaml
      with:
        working-directory: ./04PracticeProject
