name: Use Reusable Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - matrix

jobs:
    test:
      uses: ./.github/workflows/reusable-test.yaml
      with:
        working-directory: ./04PracticeProject
    build:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./04PracticeProject
      needs: test
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Cache dependencies
          id: cache-npm
          uses: actions/cache@v4
          with:
            path: ./04PracticeProject/node_modules
            key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        - name: Install dependencies
          if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
          run: npm ci
        - name: Build application
          run: npm run build
        - name: Upload build artifacts
          uses: actions/upload-artifact@v4
          with:
            name: build-artifacts
            path: |
              ./04PracticeProject/dist
    deploy:
      needs: build
      uses: ./.github/workflows/reusable-deploy.yaml
      with:
        working-directory: ./04PracticeProject
