name: "First workflow"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello!"
          echo "Further greetings"
      - name: Print goodbye
        run: echo "Bye!"
